In [6]:
import pandas as pd

In [10]:
df = pd.read_csv('output.csv')

In [16]:
df.head(5)

,City,district,Адрес,street,zh_k_name,photos,monthlyExpensePerPerson,moveInStart,ownername,active,...,keyduplicate,postviewers,postdate,channelname,message,author_name,date,message_link,channel_name,views
0,Алматы,Алмалинский,Алмалинский район по Толе-би,Толе-би,NaN,[],NaN,NaN,NaN,NaN,...,NaN,1102,2024-10-07 19:21:44,@kvartira_v_almaty,Сдаются 2 комнаты изолированные в 3 комнатной ...,kvartira_v_almaty,2024-10-07 19:21:44,https://t.me/@kvartira_v_almaty/22087,@kvartira_v_almaty,1102
1,Алматы,NaN,Егизбаева 5к2,Егизбаева,Ala Park,[],65000.0,NaN,NaN,True,...,False,1057,2024-10-07 18:50:42,@kvartira_v_almaty,В 2-комнатную квартиру нужна 1 девушка. \nОпла...,kvartira_v_almaty,2024-10-07 18:50:42,https://t.me/@kvartira_v_almaty/22080,@kvartira_v_almaty,1057
2,Алматы,NaN,Тимирязова Гагарина,Тимирязова,NaN,[],75000.0,NaN,NaN,True,...,False,1005,2024-10-07 17:34:05,@kvartira_v_almaty,Сдается одна большая изолированная комната в т...,kvartira_v_almaty,2024-10-07 17:34:05,https://t.me/@kvartira_v_almaty/22068,@kvartira_v_almaty,1005
3,Алматы,NaN,"Алматы, Мега, Саяхат, Жаs Канат",NaN,NaN,[],NaN,NaN,NaN,True,...,NaN,991,2024-10-07 17:25:26,@kvartira_v_almaty,Срочно Подселениеге \n2-кыз керек \nТребование...,kvartira_v_almaty,2024-10-07 17:25:26,https://t.me/@kvartira_v_almaty/22067,@kvartira_v_almaty,991
4,Алматы,Коктем-3,"Квартира находится в Коктем-3, дом 1 (Бухар Жы...",Бухар Жырау Весновка,NaN,[],125000.0,2024-10-20,NaN,True,...,NaN,1052,2024-10-07 16:07:16,@kvartira_v_almaty,Ищу на подселение в изолированную комнату одну...,kvartira_v_almaty,2024-10-07 16:07:16,https://t.me/@kvartira_v_almaty/22066,@kvartira_v_almaty,1052

In [18]:
excel_file = "output.xlsx"
df.to_excel(excel_file, index=False, engine='openpyxl')